const data = [
    [2, 'Team Amigos', 'Amruta Misal', 'Nachiket Suryawanshi', 'Vaishnavi Kondewar'],
    [24, 'Blue Peace', 'Sourav Yewale', 'Shruti Jangalgi', 'Parth Suryawanshi', 'Ishwar Bidarkar'],
    [32, 'Defenders', 'KaushaL Gawas', 'Sainath Balkawade'],
    [32, 'Hawks', 'Prathamesh Yadav', 'Anish Dubey', 'Himanshu Wankar'],
    [19, 'Hydroponic and Aquaponics', 'Pranav Khamkar', 'Kewal Parekh', 'Nikhil Jadhav'],
    [32, 'Mind Install',
        'Sharvari Chikane',
        'Aayush Gavale',
        'Sushmita mali',
        'Saurabh Shrivastava',
    ],
    [32, 'No Poverty',
        'Nishant Pawar',
        'Vivek Chavan',
    ],
    [32, 'Olimpics',
        'Marlaplle Pooja',
        'Darshana Kambli',
    ],
    [29, 'RKM',
        'Rishi Raj',
        'Komal Memane',
        'Mrunal nigade',
    ],
    [32, 'Solvers',
        'Sardar Sushanta',
        'Akash verma',
        'Basant Shivdhani',
    ],
    [11, 'System Breakers',
        'Pranali Sakpal',
        'Bhalekar Viraj',
        'Roshan kumbharkar',
    ],
    [8, 'Team Saviour',
        'Rutik Bhandalkar',
        'Snehal jituri',
        'Niranjan Bhoi',
        'Samiksha Khopade',
    ],
    [12, 'Team Shark',
        'Omkar Gadale',
        'Rohan Kalekar',
        'Borkar Mahendra',
    ],
    [14, 'Team WB',
        'Faique Khan',
        'Udaykiran Pandugayala',
        'Velankanni Yadavar',
        'Prajwal Manjare',
    ],
    [32, 'Team Foundation',
        'Tejas Bitale',
        'Chavan Aditya',
        'Bankar Aniket',
    ],
    [5, 'TroubleShooters',
        'Supriya Kanse',
        'Jadhav tejaswini',
        'Saba Sayyed',
        'Sagvekar Sanjana',
    ],
    [7, 'Vision of 4',
        'Athira K',
        'Sayali Selukar',
        'Jerusha Gaikwad',
        'Dhanshree Gandas',
    ],
    [32, 'TVS Trio',
        'Vaishnavi Palande',
        'Srithin Nair',
        'Toshit Aditya'
    ],
    [16, 'The Optimizers',
        'Tamhane Anushka',
        'Chaudhari Vaibhavi',
        'Hrishikesh Tambe',
        'Amey Karale'
    ],
    [32, 'Tradix Network',
        'Sourav Jagtap',
        'Sahil Madavi',
        'Girish Bansode',
        'Omkar Nanaware',
    ],
    [32, 'Solution Squad',
        'Faizan Kalkoti',
        'Swanand Muley',
        'Prasanna Shinde',
        'Chandan Patil'
    ],
    [4, 'Change Creators',
        'Rushi Pol',
        'Omkar Mahangare',
        'Harshikesh shinde',
        'Pranjali Nalawade'
    ],
    [20, 'Team Stay Green',
        'Shaikh Muhammed',
        'Hamza Shaikh',
        'Syed Mohammad',
        'Mohammad Danish'
    ],
    [18, 'Team Invincible',
        'Soham thodge',
        'Sumit Patil',
        'Yash Lonkar',
        'Anushka Katkade'
    ],
    [28, 'Team Avengers',
        'Rokade Arun',
        'Aditi Chavan',
        'Rohan Praep Kudale',
        'Shivani Lokhande',
    ],
    [30, 'The Rescuers',
        'Devkumar Bharti',
        'Swaraj kendre',
        'Shantanu Londhe',
        'Ajinkya Masal',
    ],
    [13, 'Team Rebels',
        'Akshaya surwase',
        'Sakhare Atharv',
        'Akshay Daaji Konale',
        'Pradnya Yadav',
    ],
    [27, 'Innowards',
        'Ãshwin',
        'Atharva Garde',
        'Sakshi Terwade',
        'Shashank Kothaly',
    ],
    [21, 'Hell God',
        'Adsul Prathamesh',
        'Shivraj Yewale',
        'Chaitanya Kumbhar',
        'Sujit Khade',
    ],
    [1, 'Leading Edge',
        'Sakshi Mavalkar',
        'More Aditya',
    ],
    [15, 'Team Experts',
        'Nishadh Nikam',
        'Shahid Inamdar',
        'Chandan Ankalgi',
        'Tambe Amar',
    ],
    [17, 'Skill Setters',
        'Dhaval Thaware',
        'Adnan Sayyad',
        'Sahil Jadhav',
        'Aditya Jagtap',
    ],
    [31, 'Planet Savers',
        'Bhagat Aishwarya',
        'Sara Mali',
        'Samiksha Fargade',
        'Kamthekar Supriya',
    ],
    [9, 'Spartan',
        'Prajwal Deshpande',
        'Akash Kolekar',
        'Tejas Chikane',
        'Mandar Karnik',
    ],
    [3, 'Team Elite',
        'Sanika Jagdale',
        'Vishal Joshi',
        'Yash Gangan',
        'Sakshi Nevase',
    ],
    [32, 'GG Chasers',
        'Bhavika Sharma',
        'Shreyash Waghmare',
        'Siddhant Ladkat',
        'Aboli Mohite',
    ],
    [25, 'Mind Blenders',
        'Rajure Vinayak',
        'Sarthak Boralkar',
        'Dhanashree shinde',
        'Mohammad Abubaker',
    ],
    [10, 'Worthy Crew',
        'Adesh Badade',
        'Rohan Tathe',
        'Bali Siddheshwar',
        'Tushar sul',
    ],
    [6, 'Magnetic Brains',
        'Aniket Behera',
        'Dhanashri dudhal',
        'Samyak Dhole',
        'Vaishnavi Ramgir',
    ],
    [23, 'Iconic',
        'Sakshi Ingle',
        'Waghmode Mahesh',
        'Zaid Pathan',
        'Vaishnavi pare',
    ],
    [32, 'Black Eagle',
        'Vaibhav Jagtap',
        'Suraksha vedpathak',
        'Bhagwat Samiksha',
        'Jadhav Prachi',
    ],
    [32, 'Team Unique',
        'Todkar Shivam',
        'Mhase Siddhi',
        'Hawale Makarand',
        'Tirthesh Pol',
    ],
    [26, 'Hustlers',
        'Sarrah Burmawala',
        'Faheem Khalique',
        'Archana Zagade',
    ],
    [22, 'Aqua Saviours',
        'Deokar Ritesh',
        'Sarthak Mali',
        'Shivpuje Vilas',
        'Monika S'
    ],
]


data.sort((a, b) => a[0] - b[0]);

var btns = document.querySelectorAll('.btn');

var current = document.querySelector('.active');
document.getElementById(current.name).style = "display: initial";

const tbody = document.getElementById('tbody');

data.forEach(team => {
    j = 2
    l = team.length;
    if (team[0] == 32)
        s = '<th>' + '-' + '</th>';
    else
        s = '<th>' + team[0] + '</th>';
    s += '<th>' + team[1] + '</th>'
    for (i = 2; i < 6; i++) {
        if (j < l) {
            s += '<td>' + team[j] + '</td>'
        } else {
            s += '<td>-</td>';
        }
        j += 1;
    }
    tbody.innerHTML += '<tr class="want-hover">' + s + '</tr>';
})


btns.forEach(btn => {
    btn.addEventListener('click', function () {
        var current = document.querySelector('.active');
        current.className = current.className.replace(' active');
        this.className += ' active';
        document.getElementById(current.name).style = "display: none";
        document.getElementById(this.name).style = "display: initial";
    })
});