const data = [
    ['Team Amigos', 'Amruta Misal', 'Nachiket Suryawanshi', 'Vaishnavi Kondewar'],
    ['Blue Peace', 'Sourav Yewale', 'Shruti Jangalgi', 'Parth Suryawanshi', 'Ishwar Bidarkar'],
    ['Defenders', 'KaushaL Gawas', 'Sainath BALKAWADE'],
    ['Hawks', 'Prathamesh Yadav', 'Anish Dubey', 'Himanshu Wankar'],
    ['Hydroponic and Aquaponics', 'Pranav Khamkar', 'Kewal Parekh', 'Nikhil Jadhav'],
    ['Mind Install',
        'Sharvari Chikane',
        'Aayush Gavale',
        'Sushmita mali',
        'Saurabh Shrivastava',
    ],
    ['No Poverty',
        'Nishant Pawar',
        'Vivek Chavan',
    ],
    ['Olimpics',
        'Marlaplle Pooja',
        'Darshana Kambli',
    ],
    ['RKM',
        'Rishi Raj',
        'Komal Memane',
        'Mrunal nigade',
    ],
    ['Solvers',
        'Sardar Sushanta',
        'Akash verma',
        'Basant Shivdhani',
    ],
    ['System Breakers',
        'Pranali Sakpal',
        'Bhalekar Viraj',
        'Roshan kumbharkar',
    ],
    ['Team Saviour',
        'Rutik Bhandalkar',
        'Snehal jituri',
        'Niranjan Bhoi',
        'Samiksha Khopade',
    ],
    ['Team Shark',
        'Omkar Gadale',
        'Rohan Kalekar',
        'Borkar Mahendra',
    ],
    ['Team WB',
        'Faique Khan',
        'Udaykiran Pandugayala',
        'Velankanni Yadavar',
        'Prajwal Manjare',
    ],
    ['Team Foundation',
        'Tejas Bitale',
        'Chavan Aditya',
        'Bankar Aniket',
    ],
    ['TroubleShooters',
        'Supriya Kanse',
        'Jadhav tejaswini',
        'Saba Sayyed',
        'Sagvekar Sanjana',
    ],
    ['Vision of 4',
        'Athira K',
        'Sayali Selukar',
        'Jerusha Gaikwad',
        'Dhanshree Gandas',
    ],
    ['TVS Trio',
        'Vaishnavi Palande',
        'Srithin Nair',
        'Toshit Aditya'
    ],
    ['The Optimizers',
        'Tamhane Anushka',
        'Chaudhari Vaibhavi',
        'Hrishikesh Tambe',
        'Amey Karale'
    ],
    ['Tradix Network',
        'Sourav Jagtap',
        'Sahil Madavi',
        'Girish Bansode',
        'Omkar Nanaware',
    ],
    ['Solution Squad',
        'Faizan Kalkoti',
        'Swanand Muley',
        'Prasanna Shinde',
        'Chandan Patil'
    ],
    ['Change Creators',
        'Rocky Plays',
        'Omkar Mahangare',
        'Harshikesh shinde',
        'Pranjali Nalawade'
    ],
    ['Team Stay Green',
        'Shaikh Muhammed',
        'Hamza Shaikh',
        'Syed Mohammad',
        'Mohammad Danish'
    ],
    ['Team Invincible',
        'Soham thodge',
        'Sumit Patil',
        'Yash Lonkar',
        'Anushka Katkade'
    ],
    ['Team Avengers',
        'Rokade Arun',
        'Aditi Chavan',
        'Rohan Praep Kudale',
        'Shivani Lokhande',
    ],
    ['The Rescuers',
        'Devkumar Bharti',
        'Swaraj kendre',
        'Shantanu Londhe',
        'Ajinkya Masal',
    ],
    ['Team Rebels',
        'Akshaya surwase',
        'Sakhare Atharv',
        'Akshay Daaji Konale',
        'Pradnya Yadav',
    ],
    ['Innowards',
        'Ãshwin',
        'Atharva Garde',
        'Sakshi Terwade',
        'Shashank Kothaly',
    ],
    ['Hell God',
        'Adsul Prathamesh',
        'Shivraj Yewale',
        'Chaitanya Kumbhar',
        'Sujit Khade',
    ],
    ['Leading Edge',
        'Sakshi Mavalkar',
        'More Aditya',
    ],
    ['Team Experts',
        'Nishadh Nikam',
        'Shahid Inamdar',
        'Chandan Ankalgi',
        'Tambe Amar',
    ],
    ['Skill Setters',
        'Dhaval Thaware',
        'Adnan Sayyad',
        'Sahil Jadhav',
        'Aditya Jagtap',
    ],
    ['Planet Savers',
        'Bhagat Aishwarya',
        'Sara Mali',
        'Samiksha Fargade',
        'Kamthekar Supriya',
    ],
    ['Spartan',
        'Prajwal Deshpande',
        'Akash Kolekar',
        'Tejas Chikane',
        'Mandar Karnik',
    ],
    ['Team Elite',
        'Sanika Jagdale',
        'Vishal Joshi',
        'Yash Gangan',
        'Sakshi Nevase',
    ],
    ['GG Chasers',
        'Bhavika Sharma',
        'Shreyash Waghmare',
        'Siddhant Ladkat',
        'Aboli Mohite',
    ],
    ['Mind Blenders',
        'Rajure Vinayak',
        'Sarthak Boralkar',
        'Dhanashree shinde',
        'Mohammad Abubaker',
    ],
    ['Worthy Crew',
        'Adesh Badade',
        'Rohan Tathe',
        'Bali Siddheshwar',
        'Tushar sul',
    ],
    ['Magnetic Brains',
        'Aniket Behera',
        'Dhanashri dudhal',
        'Samyak Dhole',
        'Vaishnavi Ramgir',
    ],
    ['Iconic',
        'Sakshi Ingle',
        'Waghmode Mahesh',
        'Zaid Pathan',
        'Vaishnavi pare',
    ],
    ['Black Eagle',
        'Vaibhav Jagtap',
        'Suraksha vedpathak',
        'Bhagwat Samiksha',
        'Jadhav Prachi',
    ],
    ['Team Unique',
        'Todkar Shivam',
        'Mhase Siddhi',
        'Hawale Makarand',
        'Tirthesh Pol',
    ],
    ['Hustlers',
        'Sarrah Burmawala',
        'Faheem Khalique',
        'Archana Zagade',
    ],
    ['Aqua Saviours',
        'Deokar Ritesh',
        'Sarthak Mali',
        'Shivpuje Vilas',
        'Monika S'
    ],
]

var btns = document.querySelectorAll('.btn');

var current = document.querySelector('.active');
document.getElementById(current.name).style = "display: initial";

const tbody = document.getElementById('tbody');

data.forEach(team => {
    j = 1
    l = team.length;
    s = '<th>' + team[0] + '</th>'
    for (i = 1; i < 5; i++) {
        if (j < l) {
            s += '<td>' + team[j] + '</td>'
        } else {
            s += '<td>-</td>';
        }
        j += 1;
    }
    tbody.innerHTML += '<tr class="want-hover">' + s + '</tr>';
})


btns.forEach(btn => {
    btn.addEventListener('click', function () {
        var current = document.querySelector('.active');
        current.className = current.className.replace(' active');
        this.className += ' active';
        document.getElementById(current.name).style = "display: none";
        document.getElementById(this.name).style = "display: initial";
    })
});